### ISSUE TITLE
Enhance schema files to prevent schema validation issues

### ISSUE THREAD

**Issue by cindyzh-ibm** [elyra-ai/pipeline-schemas#33]
@tomlyn @matthoward366 @vlad-bunescu 

This is a request to alter some of the pipeline-schema files to prevent schema validation errors from icorrectly occurring: 

1, pipeline-flow-v3-schema.json needs to rewrite the app_data
app_data for overall pipeline, pipeline_def, execution_node_def, supernode_def, binding_entry_node_def, binding_exit_node_def, model_node_def, port_def, bound_port_def, link_def, and runtime_def uses 
![image](https://user-images.githubusercontent.com/64796288/93143033-fcceda80-f69b-11ea-8c25-8440e0c5e90d.png)

And here is the definition of app_data
![image](https://user-images.githubusercontent.com/64796288/93143092-18d27c00-f69c-11ea-96f1-9e3a5c60b11a.png)

And each of the definition in the pipeline-flow-ui-v3-schema.json allows additional properties. 

This app_data specification makes it impossible for a validation tool to find what is the corresponding schema to check in the pipeline-flow-ui-v3-schema.json for a certain entity. It ends with nothing is validated for the schema defined in the pipeline-flow-ui-v3-schema.json.

2, pipeline-flow-ui-v3-schema.json
a, "required": [] in the definitions.runtime_info_def is not acceptable by Java Json Tool.
The validate requires there must be one element in the array. 
As it is empty array, it is no needed to specified. 

b, definitions.node_info_def.properties.messages.descriptions should be
definitions.node_info_def.properties.messages.description

3, pipeline-connection-v3-schema.json
app_data points back to pipeline-flow-v3-schema.json app_data. However, none of app_data definition in the pipeline-flow-v3-schema.json is for connection app_data.

4, datarecord-metadata-v3-schema.json
"required": [] in the definitions.runtime_info_def is not acceptable.
The validate requires there must be one element in the array. 
As it is empty array, it is no needed to specified.

**Comment by tomlyn** [comment]
@cindyzh-ibm I know is a separate thread for this issue you said you had used  “JSON schema validation tools.” that had caused errors with the current schema files. What are they?

In common canvas  we use  [jsonschema](https://www.npmjs.com/package/jsonschema) to validate incoming and outgoing pipelineFlow and palette documents and that doesn’t have any problems with the current pipleine-flow-v3-schema.json and pipeline-flow-ui-v3-schema.json files.  

If we make changes to the schema files we'll have to make sure it doesn't break anything in common-canvas.

**Comment by cindyzh-ibm** [comment]
Java Json Tool library and networknt library

**Comment by tomlyn** [comment]
Changes from PR merged.

**Comment by cindyzh-ibm** [comment]
@tomlyn Thanks a lot for reviewing and approved the PR.
