### ISSUE TITLE
V3 Parameter set and parameter schema change and v3 pipeline schema change to reference the new parameter set schema

### ISSUE THREAD

**Issue by cindyzh-ibm** [elyra-ai/pipeline-schemas#69]
Propose v3 schema change for Parameter set and parameter. 
Also propose v3 pipeline schema change to reference new parameter set schema

Here is the corresponding pull request https://github.com/elyra-ai/pipeline-schemas/pull/63

FYI @matthoward366

**Comment by matthoward366** [comment]
merged
