### ISSUE TITLE
Change comment's minimum width and height

### ISSUE THREAD

**Issue by VenkatArra** [elyra-ai/pipeline-schemas#82]
pipeline-flow-ui-v3-schema.json has minimum width and height as 10. It should be changed to 0 as pipeline flow fails when comment's height/width is less than 10.
fyi @matthoward366

**Comment by tomlyn** [comment]
@VenkatArra 
I don't understand why this is a problem. If the minimum is allowed to be 0 the comment would not be visible on the canvas. A minimum of 10 pixels doesn't seem unreasonable. Can you explain the need for this change?

**Comment by VenkatArra** [comment]
@tomlyn One of the comments added from the canvas UI had height/width as 6 in the pipeline json. And this resulted in errors during schema validation. So we wanted to change the minimum to 0. I asked for more details. But do you have any suggestion on how to fix this? Thanks.

**Comment by tomlyn** [comment]
@VenkatArra 
Hi Venkat, when you say "canvas UI " do you mean the common-canvas UI?  Elyra Canvas (common-canvas) allows a minimum of 20px x 20px for comments which, even at that size doesn't allow the display of a single character.
<img width="77" alt="image" src="https://user-images.githubusercontent.com/15114439/127556546-12bdc68e-6246-41a4-8b81-9b2fcb4ea5d8.png">
If somehow the UI is allowing a size smaller than 20x20 to be created I will fix it if you open an issue and explain how that can be reproduced.

**Comment by tomlyn** [comment]
@VenkatArra   Any news on this?

**Comment by VenkatArra** [comment]
Hi @tomlyn Sorry I was away last week and couldn't respond. This is DataStage canvas UI. I am still waiting for the inputs from them. We can keep this on hold until we hear something. Thanks.

**Comment by VenkatArra** [comment]
Hi @tomlyn I still didn't get any update from the datastage UI team. Closing for now and will reopen as needed.
